url:
  rails_tut: "https://www.railstutorial.org/"
  rails_tut_book: "https://www.railstutorial.org/book"
  rails_tut_help: "https://www.railstutorial.org/help"
  rails_tut_contact: "https://www.railstutorial.org/contact"
  screencast: "http://screencasts.railstutorial.org/"
  rails: "http://rubyonrails.org/"
  new_rails: "http://news.railstutorial.org/"
  michael_hartl: "http://www.michaelhartl.com/"
validates:
  name_max: 50
  email_max: 255
  password_min: 6
  mail_regex: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
